### ISSUE TITLE
No typing bar showed during drill trials

### ISSUE THREAD

**Issue by Wei940127** [memphis-iis/mofacts#1360] opened 2024-01-05 16:10 UTC
The typing bar was missing during drill trials in the assessment unit. Please see the following image.
![missing typing bar for drill trial](https://github.com/memphis-iis/mofacts/assets/54991536/de02daa7-c22e-46c6-8ced-f6f8e6dcb587)

**Comment by JRustyHaner** [comment] 2024-01-08 15:04
@Wei940127 I am running your tdf and cannot reproduce the issue:

![image](https://github.com/memphis-iis/mofacts/assets/46696077/83503687-ccb1-4403-9f71-48db13aa0168)

(I did see fork- and an input box) . Could you try to reproduce it and give me a screenshot of the console log if it happens again?

**Comment by Wei940127** [comment] 2024-01-08 16:27
@JRustyHaner I just tried again and the typing bar showed this time. Not sure what happened last Friday.

**Comment by JRustyHaner** [comment] 2024-01-08 16:32
@Wei940127 I'm going to go ahead and close this. Let us know if it happens again!

**Closed by JRustyHaner** 2024-01-08 16:32 UTC
Labels: bug, Highest, staging
